Repository GoogleChromeLabs/wpp-research, pull requests merged in 2024-11, with the labels that each got.

#162 Implement SQL query to compare impact of using auto-sizes plugin for `sizes=auto` functionality
  sql/2024/10/auto-sizes-impact-before-after.sql
  sql/README.md
Labels: sql query

#165 Fix appending `rnd` query parameter to URLs in benchmark-server-timing
  cli/commands/benchmark-server-timing.mjs
Labels: bug

#164 Allow specifying the viewport dimensions when running benchmark-web-vitals
  cli/README.md
  cli/commands/benchmark-web-vitals.mjs
Labels: enhancement
